<?php
	require_once(getcwd()."/resources/config.php");
	require_once(DOCUMENT_ROOT."/modules/view/header.php");
?>
<?php
	if(isset($_COOKIE["user_id"]))
?>
<?php
	require_once(DOCUMENT_ROOT."/modules/view/footer.php");
?>
